apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jonathanvdwatt/argo-examples.git
    targetRevision: HEAD
    path: app-of-apps/solar-system/solar-system-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true